apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-worker-23897
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/service-worker-23897
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
